# this is only for development purposes and integration with visual studio code
version: '3.4'
volumes:
  runs: {}
services:
  fv3:
    depends_on:
      - tensorboard
    image: us.gcr.io/vcm-ml/prognostic_run
    entrypoint: []
    command: [ls]
    volumes:
      - ../../:/fv3net
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/key.json
      - runs:/data
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json
  tensorboard:
    image: tensorflow/tensorflow
    volumes:
        - runs:/data
    ports:
      - 6006:6006
    command: tensorboard --logdir=/data --bind_all
  fv3net_dev:
    image: us.gcr.io/vcm-ml/prognostic_run:ad102a241fa060338d31ec9b3503b94b82cc16d7
    entrypoint: []
    command: [bash]
    volumes:
      - .:/fv3net/workflows/prognostic_c48_run
      - ../../external/fv3fit:/fv3net/external/fv3fit
      - ../../external/loaders:/fv3net/external/loaders
      - ../../external/fv3gfs-fortran:/tmp/fortran-build
      - ../../external/fv3gfs-wrapper:/fv3net/external/fv3gfs-wrapper
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json
